# Generated by Django 4.1.2 on 2022-10-27 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pon el nombre del género.', max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='director',
            old_name='biografia',
            new_name='biography',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='nombre',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='numero_oscars',
            new_name='oscars',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='apellidos',
            new_name='surname',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='duracion',
            new_name='length',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='fecha_estreno',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='pelicula',
            old_name='nombre',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='peliculas.director'),
        ),
        migrations.AddField(
            model_name='pelicula',
            name='genere',
            field=models.ManyToManyField(to='peliculas.genere'),
        ),
    ]
